### ISSUE TITLE
バックアップデータが5.8Mあり、データ移行ができません。

### ISSUE THREAD

**Issue by Koichiro3** [EC-CUBE/data-migration-plugin#1]
お世話になります。書込の方法すら分からない状態での書込、申し訳ありません。

webshopオーナーです。
この度、2.13.5のwebshopを4.0.1に移行しようとしております。
なぜか、dtb_order_temp.csvが4.1MBもあり、バックアップデータ総量が5.8MBになっています。
バックアップデータの容量規制を少し緩めて頂くか、dtb_order_temp.csv等を初めとするでーたの減量の方法があれば、ご教授頂きたいと思っております。
古い（数年前）のバックアップデータからのデータ移行は、今のところ問題なく進んでいるようです。
ありがとうございます。

**Comment by nobuhiko** [comment]
バックアップデータの容量規制はしておりません。
PHPの設定でファイルのアップロードを5.8MB以上出来るように設定してください
https://www.php-factory.net/trivia/05.php

**Comment by Koichiro3** [comment]
ご返信ありがとうございました。
では、こちらのサーバーの設定なのですね。

本当に申し訳ありませんでした。
設定を触ってみます。

ありがとうございます。

2019/02/25 12:08、Nobuhiko Kimoto <notifications@github.com> のメール：

> バックアップデータの容量規制はしておりません。
> PHPの設定でファイルのアップロードを5.8MB以上出来るように設定してください
> https://www.php-factory.net/trivia/05.php
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

ｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰ
植村印刷データ
植村 浩一郎
TEL 0745-72-7707  FAX 0745-72-7805
携帯 090-3269-7150　E-mail upd@myad.jp

**Comment by nobuhiko** [comment]
2.13.5系のdtb_order_tempは削除してしまっても構いませんので、DBから古い分を削除していただいても問題はないと思います

**Comment by Koichiro3** [comment]
あ、個人情報が出てしまったので、一度書込を削除させて頂きます。ごめんなさい。

**Comment by Koichiro3** [comment]
ご返信ありがとうございました。 
では、こちらのサーバーの設定なのですね。 
本当に申し訳ありませんでした。 
設定を触ってみます。

 ありがとうございます。
