### ISSUE TITLE
受注一覧で表示されている受注データのお届け先が【Not null violationNot null violation】になっている

### ISSUE THREAD

**Issue by kanako-kina** [EC-CUBE/data-migration-plugin#10]
## 概要(Overview)
受注一覧で表示されている受注データのお届け先が【Not null violationNot null violation】になっている。

## 再現手順(Procedure)
+ 2.11系でテスト用の[会員、管理者、商品、カテゴリ、受注、支払方法、配送方法、税設定、メルマガテンプレート]データを作成
+ 2.11系でバックアップデータを作成。
+ 4系の環境にバックアップデータを引継ぐ。
+ 管理画面で受注一覧開くと、お届け先の箇所が【Not null violationNot null violation】になっている

### 移行前環境 (environment)
+ EC-CUBE：2.11.5
+ DB:
  - PostgreSQL 9.2.23
+ PHP：5.4.16

### 移行後環境 (environment)
+ EC-CUBE：4.0.2
+ DB:
  - PostgreSQL 9.2.24
+ PHP：7.1.21

### バックアップファイル
[2.11.5-pgsql-backup (1).tar.gz](https://github.com/EC-CUBE/data-migration-plugin/files/3256414/2.11.5-pgsql-backup.1.tar.gz)

**Comment by nobuhiko** [comment]
修正しました

**Comment by kanako-kina** [comment]
修正されていることを確認しました。
ご対応いただきありがとうございます。
