### ISSUE TITLE
２系、３系からのデータ移行時に一部の会員データが消えることがある

### ISSUE THREAD

**Issue by tatsuishi** [EC-CUBE/data-migration-plugin#104]
２系、３系からのデータ移行時、dtb_customer.secret_keyの値をmt_rand関数で生成している
https://github.com/EC-CUBE/data-migration-plugin/blob/4.2/Controller/Admin/ConfigController.php#L403-L404

mt_randは特定範囲で乱数を生成する関数なので重複が発生しうる
mysqlでのデータ登録時にREPLACE INTOを使用しており、ユニークキー制約があるdtb_customer.secret_keyで重複が発生した場合、先に登録されていたレコードが削除されることになる

コミュニティの報告
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=28109&forum=16&viewmode=flat&order=ASC&start=0

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/data-migration-plugin/pull/107 で修正
