### ISSUE TITLE
2.13系から移行すると、商品一覧ページを表示する際にシステムエラーが発生する

### ISSUE THREAD

**Issue by kanako-kina** [EC-CUBE/data-migration-plugin#11]
## 概要(Overview)
2.13系で作成したバックアップデータを4系で引き継いだ後、管理画面で商品一覧ページを開くとシステムエラーになる。

## 再現手順(Procedure)
+ 2.13系でテスト用の[会員、管理者、商品、カテゴリ、受注、支払方法、配送方法、税設定、メルマガテンプレート]データを作成
+ 2.13系でバックアップデータを作成。
+ 4系の環境にバックアップデータを引継ぐ。
+ 管理画面で 商品管理 > 商品一覧を開くとシステムエラー発生

### 移行前環境 (environment)
+ EC-CUBE：2.13.5
+ DB:
  - PostgreSQL 9.2.23
+ PHP：5.4.16

### 移行後環境 (environment)
+ EC-CUBE：4.0.2
+ DB:
  - PostgreSQL 9.2.24
+ PHP：7.1.21

### エラー発生時のログ
[エラー発生時のログ.txt](https://github.com/EC-CUBE/data-migration-plugin/files/3256479/default.txt)

**Comment by nobuhiko** [comment]
再現しないです

**Comment by hiro-t59** [comment]
2系にて作成した税設定の有効日時(JST)が移行後に(JST)のまま4系に保存されており、
UTCで参照することで、＋9時間のズレが発生した。
上記より、有効な税設定がないと判断されたことにより、システムエラーが発生。
以下のcommitで修正されていることを確認。

https://github.com/EC-CUBE/data-migration-plugin/commit/fdddc9ef6e3dcbc038bd333414cd835eea53547b

https://github.com/EC-CUBE/data-migration-plugin/commit/f9c6a0122f84ea2c98c9187305cc7eb837369555
