### ISSUE TITLE
エラーメッセージ

### ISSUE THREAD

**Issue by asing** [EC-CUBE/data-migration-plugin#13]
すみません、日本語が話せません。
EC-CUBEバージョン	2.13.1     -> 4.0.2
MySQL database

Admin 
商品管理  ->  商品一覧
![WX20190710-162312](https://user-images.githubusercontent.com/345259/60953214-4f419800-a32f-11e9-9ef2-45bd52d76b9b.png)
![WX20190710-162351](https://user-images.githubusercontent.com/345259/60953220-51a3f200-a32f-11e9-94c6-0d2c5b623ca4.png)

Front site
https://xxxxxx.com/products/list?category_id=13
![WX20190710-162647](https://user-images.githubusercontent.com/345259/60953296-7ef0a000-a32f-11e9-82b0-e726ec894c42.png)
![WX20190710-162732](https://user-images.githubusercontent.com/345259/60953357-99c31480-a32f-11e9-8cd2-008e546b066f.png)

**Comment by nobuhiko** [comment]
What is the tax rate?
設定 -> 店舗設定 -> 税率設定

maybe fixe 
add tax rule
設定 -> マスタデータ管理
mtb_rounding_type
same 2.13 ids

**Comment by asing** [comment]
Hello

設定 -> 店舗設定 -> 税率設定
![QQ20190711-082608](https://user-images.githubusercontent.com/345259/61013542-a2f6c480-a3b5-11e9-9da6-86110a9c3701.png)

設定 税率 to 0

It's looks like right, not error.

Thanks a lot

**Comment by asing** [comment]
Hello

I am test the shop checkout process.

A new error has occurred

![WX20190711-085340](https://user-images.githubusercontent.com/345259/61014314-6f1d9e00-a3b9-11e9-8b4d-ed07c84c80d0.png)

![WX20190711-085449](https://user-images.githubusercontent.com/345259/61014329-82c90480-a3b9-11e9-9594-c907abb1b625.png)


店舗設定    支払方法一覧
![WX20190711-085519](https://user-images.githubusercontent.com/345259/61014408-e18e7e00-a3b9-11e9-919b-d196c6dd7d95.png)


店舗設定  配送方法一覧
![WX20190711-085629](https://user-images.githubusercontent.com/345259/61014369-c02d9200-a3b9-11e9-8827-d75a038e745b.png)


Can you give me some help?
Thanks.

**Comment by nobuhiko** [comment]
You can not use old payment.
Please create a new one.

**Comment by asing** [comment]
OK

Add a new 支払方法
Add a new 配送方法
It's looks like right, not error.

Thanks a lot
