### ISSUE TITLE
mtb_order_status problem.

### ISSUE THREAD

**Issue by asing** [EC-CUBE/data-migration-plugin#15]
Hello
I am have a new problem.

ec-cube 2 move to ec-cube 4, mtb_order_status can't be moved ?

 I am create new mtb_order_status can't be save it .

![WX20190716-111001](https://user-images.githubusercontent.com/345259/61263159-81814880-a7ba-11e9-91ec-57e9985b31c7.png)

The history order detail show error.

![WX20190716-111244](https://user-images.githubusercontent.com/345259/61263212-a970ac00-a7ba-11e9-94f9-ffe3d50de358.png)
![WX20190716-111218](https://user-images.githubusercontent.com/345259/61263214-aa094280-a7ba-11e9-809c-3532e2e53345.png)

助けてください、感謝します。

**Comment by asing** [comment]
Hello.

This looks like a system error
I reinstalled the ec-cube 4.0.2, no plugins installed
Still have this error.

![WX20190716-171524](https://user-images.githubusercontent.com/345259/61282113-56fcb300-a7ed-11e9-8582-74db08eb5c78.png)

**Comment by nobuhiko** [comment]
This is a specification.
