### ISSUE TITLE
PASSWORD_HASH_ALGOSについてREADMEに記載

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/data-migration-plugin#16]
PASSWORD_HASH_ALGOSの値は、環境によって異なる
https://github.com/EC-CUBE/eccube-2_13/blob/eccube-2.11.1/html/install/index.php#L951

EC-CUBE4ではSHA256が初期値となっている
https://github.com/EC-CUBE/ec-cube/blob/4.0/app/config/eccube/packages/eccube.yaml#L28

AUTH_MAGICの移行のみではログインできない場合があるので、README等で補足する

**Comment by nobuhiko** [comment]
環境によって、というより2.4系以前はsha1が使われている感じですかね

**Comment by chihiro-adachi** [comment]
@nobuhiko 
ありがとうございます、2.4系以前がsha1ですね。
READMEの補足もありがとうございます。https://github.com/EC-CUBE/data-migration-plugin/commit/5d2c6e0ffa404ec5459fbd046db57af9f2ee8787
