### ISSUE TITLE
MySQLで、税設定が移行できない。

### ISSUE THREAD

**Issue by hiro-t59** [EC-CUBE/data-migration-plugin#2]
## 概要(Overview)
MySQLで、税設定が移行できない。

## 期待する内容(Expect)  or 要望 (Requirement)
DB問わず、税設定が2系→4系に移行できる。

## 再現手順(Procedure)
1.移行元(2系)にて税設定を追加する。
2.バックアップデータを作成し、ダウンロードを行う
3.移行先(4系)にて本プラグインを用いて、データの移行を行う
4.管理画面→設定→店舗設定→税率設定を表示する

### 環境 (environment)
+ EC-CUBE: 4.0.2
+ PHP: 7.1.21
+ DB:
  - MySQL 5.5.60-MariaDB

+ EC-CUBE:2.13.5(移行元)
## 関連情報 (Ref)

**Comment by nobuhiko** [comment]
MySQL で ID 0 のものだけ移行に失敗する模様

**Comment by wdrara** [comment]
お世話になっております。
以下の３．税率設定で解決しましたが、
私と同じようにエラーで驚く人もいるかと思い投稿しておきます。
エラーの発生原因は特定できておりません(受注件数が10000件超えかな？)

１．本プラグインでデータ移行時にエラー発生(データ移行は出来てました)
２．管理画面の商品一覧や、フロント画面のカテゴリを選ぶとエラーになる。
３．税率を何かしら設定した後は、正常に動作。

環境 (environment)
・PHP：7.2
・MySQL：5.7
・移行後： 4.0.2
・移行元：2.12.2

**Comment by nobuhiko** [comment]
@hiro-t59 修正しました

**Comment by nobuhiko** [comment]
@wdrara 
税率がなにも設定されていなかったということでしょうか？
それはたぶんシステムエラーで中途半端にデータ移行がされたのだと思うので、この不具合には関係ないと思います

**Comment by wdrara** [comment]
税率設定が初期のままでした。
ありがとうございました。
