### ISSUE TITLE
データ移行後に会員情報編集で EntityNotFoundException

### ISSUE THREAD

**Issue by hironori-tanaka** [EC-CUBE/data-migration-plugin#21]
EC-CUBE2.4.1 → EC-CUBE4.0.2
データ移行プラグイン 1.4.8

会員情報編集で EntityNotFoundException Entity of type 'Eccube\Entity\Master\Job' for IDs id(0) was not found Exception が発生する

移行前には dtb_customer の job_id はすべて null だったが、なぜか移行後に job_id が 0 になってしまっている。

**Comment by hironori-tanaka** [comment]
同様に、商品情報編集でも Entity of type 'Eccube\Entity\DeliveryDuration' for IDs id(0) was not found が発生。
dtb_product_class.delivery_duration_id に 0 が入ってしまっている。

**Comment by nobuhiko** [comment]
どちらも確認できませんでした。
