### ISSUE TITLE
EC-CUBE 4.0.3環境でデータ移行プラグインが正常に動作しない

### ISSUE THREAD

**Issue by junpeko5** [EC-CUBE/data-migration-plugin#22]
## 概要(Overview)
EC-CUBE4.0.3環境で、データ移行プラグインの動作テストを行ったところ、正しく動作しなかった。
具体的にはEC-CUBE 2.13.5環境で作成したバックアップデータを、
EC-CUBE 4.0.3環境でデータ移行プラグインを利用し、バックアップデータをアップロードしたところ、システムエラーとなり、受注データが正しく移行されないことを確認。

エラーログをsite.logにて確認したところ、
`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'tax_adjust' cannot be null`
という箇所があり、4.0.2から4.0.3のバージョンアップに伴う仕様変更が影響していると思われる。

## 再現手順(Procedure)

- EC-CUBE 2.13.5でテスト用の[会員、管理者、商品、カテゴリ、受注、支払方法、配送方法、税設定、メルマガテンプレート]データを作成
- EC-CUBE 2.13.5でバックアップデータを作成。
- EC-CUBE 4.0.3環境でデータ移行プラグインを利用する。
- アップロード実行時にシステムエラーとなる。

## 移行前環境 (environment)
EC-CUBE：2.13.5
DB:
MariaDB  5.5.60
PHP：5.4.16
## 移行後環境 (environment)
EC-CUBE：4.0.3
DB:
MariaDB  5.5.60
PHP：7.2.19

**Comment by nobuhiko** [comment]
ありがとうございます、調べます

**Comment by nobuhiko** [comment]
@junpeko5 1.4.9 では発生しませんでした。不具合が起きるデータを頂きたいです。

**Comment by chihiro-adachi** [comment]
@nobuhiko 
こちらのデータで再現するかと思います。
[backup1.tar.gz](https://github.com/EC-CUBE/data-migration-plugin/files/3582373/backup1.tar.gz)

だいたいあたりはついたので、のちほどPR投げさせてもらいますね。

**Comment by nobuhiko** [comment]
@chihiro-adachi 
https://github.com/EC-CUBE/data-migration-plugin/commit/f725a1be7df84fb6df4d38be31eb6d06f2df2fbf
この修正で直ってそうな気がするのです

**Comment by chihiro-adachi** [comment]
dtb_order_itemにtax_adjustが追加された影響なので、上記とはまた別になりますね。

https://github.com/EC-CUBE/ec-cube/pull/4276

**Comment by chihiro-adachi** [comment]
@nobuhiko 
#23 でPRしました。

**Comment by nobuhiko** [comment]
@chihiro-adachi 
やはり再現はしないですね。環境依存？ MySQL 5.7.23

**Comment by chihiro-adachi** [comment]
こちらの環境はPostgreSQL 9.6.15です。
MySQLでも確認してみます。

**Comment by chihiro-adachi** [comment]
@nobuhiko 

MySQL 5.7.23で確認してみたら同じく再現しなかったです。

発行されているクエリを確認してみると、null値をINSERTしているが、dtb_order_item.tax_adjustにはdefault値の0が入っている状態でした。

調べたところMySQLではバルクインサートの際に、null値のINSERTはdefault値を適用するみたいです。
http://blog.sojiro.me/blog/2014/10/20/behavior-of-inserting-rows-at-not-null-column-on-mysql/

**Comment by nobuhiko** [comment]
なるほど。default値が設定されているので正しい挙動な気がしますが、MariaDBはまた挙動が違うんですかね。。

**Comment by chihiro-adachi** [comment]
SQL modeによってかわるみたいですね。
https://mariadb.com/kb/en/library/null-values/#inserting

**Comment by chihiro-adachi** [comment]
#23 のマージありがとうございます。
こちらのissueはクローズさせていただきます。
