### ISSUE TITLE
2.13.1から4.0.3のデータ移行時のエラーについて

### ISSUE THREAD

**Issue by shuji-yamagami-kojin** [EC-CUBE/data-migration-plugin#26]
お世話になります。
有用はプラグインの開発、ありがとうございます。

こちらのプラグインにて、2.13.1→4.0.3へ移行を試みました。

1. 既存システムの自動バックアップからautobukup_20190911.tar.gzを取得
2. ローカルに新規でECCube4をインストール
3. オーナーズストアにてプラグイン購入処理、またECCube4の管理画面よりプラグインインストール
4. 有効化→設定
5. ファイルをアップロード

するとこのエラーが出ました。
https://gyazo.com/1ca3838e27abd6048ea15a9655206994

税金関係だったため、プラグインかな、、と思ったので、スクショをとりました。
◆既存のプラグイン
https://gyazo.com/8ab2dbdc8f0250886b7c6f132f2eda2b

◆既存のモジュール
https://gyazo.com/b4e087cb147c389200ec7056070dbd8b

こちら、何か解決の糸口はありそうでしょうか。

**Comment by nobuhiko** [comment]
おそらくですが、バックアップファイルが想定しているものと違うのではないかと思います。
EC-CUBEの管理画面から出力したものでしょうか？

**Comment by shuji-yamagami-kojin** [comment]
@nobuhiko 
こちらご返信ありがとうございます。
バックアップですが、
https://gyazo.com/458631c9e52a7064068f4a53f6f5153d
こちらから取得したものになります。

**Comment by nobuhiko** [comment]
@shuji-yamagami-kojin 
解凍してみて、中にデータがちゃんとあるか確認することは出来ますか？
