### ISSUE TITLE
2.12.2から4.0.3のデータ移行時のエラーについて

### ISSUE THREAD

**Issue by You386** [EC-CUBE/data-migration-plugin#27]
お世話になります。
プラグインの開発、ありがとうございます。

こちらのプラグインにて、2.12.2→4.0.3へ移行を試みました。

１．既存システムの自動バックアップからtar.gzファイルを取得
２．ECCube4の管理画面よりプラグインインストール
３．バックアップファイルをアップロードすると「システムエラーが発生しました。」と表示されデータ移行が行えません。末尾記載ののエラーログが出ました。
４．エラーログ中ほどの「ConfigController->convertTz('2013-05-13 19:2...」という点は、dtb_customer.csvのcreate_dateカラム1行目のデータと一致していました。

こちら、何か解決の糸口はありそうでしょうか。
ご教示頂ければ有難く存じます。

 [Eccube\Log\Logger:log:64] - システムエラーが発生しました。 ["DateTimeZone::__construct(): Unknown or bad timezone ()","/home/XXXXX-net/www/eccube2019/app/Plugin/DataMigration4/Controller/Admin/ConfigController.php",1346,"#0 /home/XXXXX-net/www/eccube2019/app/Plugin/DataMigration4/Controller/Admin/ConfigController.php(1346): DateTimeZone->__construct('')\n#1 /home/XXXXX-net/www/eccube2019/app/Plugin/DataMigration4/Controller/Admin/ConfigController.php(230): Plugin\\DataMigration4\\Controller\\Admin\\ConfigController->convertTz('2013-05-13 19:2...')\n#2 /home/XXXXX-net/www/eccube2019/app/Plugin/DataMigration4/Controller/Admin/ConfigController.php(130): Plugin\\DataMigration4\\Controller\\Admin\\ConfigController->saveToC(Object(Doctrine\\DBAL\\Connection), '/home/XXXXX-net...', 'dtb_customer')\n#3 /home/XXXXX-net/www/eccube2019/app/Plugin/DataMigration4/Controller/Admin/ConfigController.php(96): Plugin\\DataMigration4\\Controller\\Admin\\ConfigController->saveCustomer(Object(Doctrine\\DBAL\\Connection), '/home/XXXXX-net...')\n#4 /home/XXXXX-net/www/eccube2019/vendor/symfony/http-kernel/HttpKernel.php(151): Plugin\\DataMigration4\\Controller\\Admin\\ConfigController->index(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Doctrine\\DBAL\\Connection))\n#5 /home/XXXXX-net/www/eccube2019/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#6 /home/XXXXX-net/www/eccube2019/vendor/symfony/http-kernel/Kernel.php(200): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#7 /home/XXXXX-net/www/eccube2019/index.php(76): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#8 {main}"] [POST, /管理画面ディレクトリ/data_migration4/config, XXX.116.114.34, https://www.XXXXX.net/管理画面ディレクトリ/data_migration4/config, Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36]

**Comment by nobuhiko** [comment]
サーバーにタイムゾーンが設定されていないか、間違っているようです
https://www.php.net/manual/ja/datetimezone.construct.php

**Comment by You386** [comment]
迅速な御回答ありがとうございます。解決致しました。

タイムゾーンを以下PHPで確認したところ未設定になっていたため、
echo date_default_timezone_get();
echo date("Y-m-d H:i:s");

php.iniにAsia/Tokyoを追加したところ解決しました。
[Date]
date.timezone = "Asia/Tokyo"

ありがとうございました。
