### ISSUE TITLE
2.13.1から4.0.3のデータ移行時のエラーについて

### ISSUE THREAD

**Issue by shuji-yamagami-kojin** [EC-CUBE/data-migration-plugin#28]
お世話になります。
先日はご教示、ありがとうございました。
大変助かりました。

あれから正常と考えられるデータを取得でき、いざ実行したのですが、
下記エラーが発生しました。
https://gyazo.com/96410fcfa89dc0ff569b412149101086

圧縮したファイルを解凍し確認したところ、
https://gyazo.com/0a1de3660e12159bcdf90a22507b6eda
dtb_baseinfoは正常に存在することは確認しました。

こちら、一度現象を見ていただくことは可能でしょうか？

**Comment by nobuhiko** [comment]
@shuji-yamagami-kojin 
2.4系用の処理を通ってしまっています
dtb_tax_rule.csv が存在しないか読み込めないのが原因だと思います

**Comment by shuji-yamagami-kojin** [comment]
@nobuhiko 
こちら早速のご連絡をありがとうございます。
確認したところ、データの中にはdtb_tax_rule.csvは存在しておりました。

```
$ ls -l dtb_tax_rule.csv 
-rwxr-xr-x@ 1 shuji  staff  314  9 19 06:40 dtb_tax_rule.csv
```

他の原因としては、何か考えられる箇所はありますでしょうか？

**Comment by nobuhiko** [comment]
@shuji-yamagami-kojin 
file_exists が false を返しているので、あるけど読み込めないってことですかね？
パーミッションが変とか？

圧縮データを貰えれば、ファイルに問題があるかは調べることが出来ます

**Comment by shuji-yamagami-kojin** [comment]
@nobuhiko 
こちら遅れました、ありがとうございます！
お送りさせていただければと思いますので、 DMをしたいのですが、
何か連絡手段はありますでしょうか？
ご指定のものがあれば合わせます:bow

**Comment by nobuhiko** [comment]
@shuji-yamagami-kojin info@nob-log.info へ送ってもらえますか？もしくはslackでDMでも構いません

**Comment by shuji-yamagami-kojin** [comment]
@nobuhiko 
こちら、メールにてお送りさせていただきました。
お手数をおかけし申し訳ございませんが、何卒よろしくお願いいたします。

**Comment by nobuhiko** [comment]
@shuji-yamagami-kojin 
頂いたデータは圧縮の仕方が間違っているので、それが原因です。
圧縮方式が正しければ問題なく取り込めました

**Comment by shuji-yamagami-kojin** [comment]
@nobuhiko 
ありがとうございます、こちら、どのように圧縮すれば取り込めましたでしょうか？

**Comment by nobuhiko** [comment]
@shuji-yamagami-kojin 
ec-cubeの基本は ` tar cvzf ../backup.tar.gz * ` です。
今コミットした修正で間違った圧縮でも取り込めるようにしましたので、その修正を取り込んでいただいても大丈夫です

**Comment by shuji-yamagami-kojin** [comment]
@nobuhiko ありがとうございます！こちらで試してみたのですが、datetimezoneの設定エラーが出まして、
取り急ぎローカルではなくサーバ上に設置してトライしてみました。
http://shortproject.alive-web.tech/fd/eccubemove.mov

するとこのような形で、何も動作しなくなってしまいました。。。

**Comment by nobuhiko** [comment]
@shuji-yamagami-kojin 
データが多いのでしばらく時間がかかると思いますが？

**Comment by shuji-yamagami-kojin** [comment]
@nobuhiko 
挙動として、画面が更新されてしまい処理がストップしてしまっている状態でして、、
先ほどお送りした動画後画面は放置していますが、変わらずな状態です

**Comment by nobuhiko** [comment]
@shuji-yamagami-kojin 
(最大 ○○M) と表記をしてあると思いますが、アップロードしているファイルの容量に対して足りていますか？

**Comment by shuji-yamagami-kojin** [comment]
@nobuhiko 
はい、アップしているファイル数は26MBになります。

**Comment by nobuhiko** [comment]
@shuji-yamagami-kojin 
debug mode にしたら何かエラーが出ませんか？
プラグインの問題ではなくおそらくサーバーの問題なので、これ以上はサポートしきれないと思います

**Comment by chihiro-adachi** [comment]
@shuji-yamagami-kojin 

自分の場合ですが、ファイルサイズが大きすぎる場合は、不要なcsvを削除して再度圧縮する、といったことをやってしのいでます。

dtb_order_temp.csv、dtb_session.csvがファイルサイズが大きく移行不要なファイルですね。

**Comment by shuji-yamagami-kojin** [comment]
@nobuhiko @chihiro-adachi ありがとうございます！
色々と削減 + メモリを増やして、一部のデータ取り込みは可能でした。

ただ途中でエラーで落ちてしまいますね。。。
php.iniの設定値の推奨値等はあるのでしょうか？

**Comment by shuji-yamagami-kojin** [comment]
こちら場違いな質問でしたね、申し訳ございません。
closeさせていただきます、ありがとうございました！
