### ISSUE TITLE
3系から移行したときに受注一覧が表示されない

### ISSUE THREAD

**Issue by wwbccwm** [EC-CUBE/data-migration-plugin#52]
EC-CUBE 3系から4系への移行を行った際に、受注一覧が真っ白になってしまいます。
データベースには、問題なく移行できているようでした。
また、管理画面からの受注登録も公開画面からの購入しても問題なく行え、データベースにも登録されます。

**Comment by nobuhiko** [comment]
@wwbccwm 真っ白とはどういう状態でしょうか？なにかエラーログは出ていますか？

**Comment by wwbccwm** [comment]
返信ありがとうございます！ソースにも何も表示されず、真っ白な画面になります。
他のメニューは問題なく表示されています。
ログには「システムエラーが発生しました」と出ていました。

["Error: Method Proxies\\__CG__\\Eccube\\Entity\\Master\\OrderStatusColor::__toString() must not throw an exception, caught Doctrine\\ORM\\EntityNotFoundException: Entity of type 'Eccube\\Entity\\Master\\OrderStatusColor' for IDs id(XXXX) was not found","/home/XXXXXXX/www/eccube/vendor/twig/twig/src/Extension/EscaperExtension.php",0,"#0 {main}"]

**Comment by nobuhiko** [comment]
なるほど。3系で受注ステータスを増やしているのが原因のようです。
マスター管理でOrderStatusColorを3系と同じようにしてあげれば動くんじゃないかと思います

**Comment by wwbccwm** [comment]
すみません、ありがとうございます。
mtb_order_status
mtb_order_status_color
上記に3系と同じ受注ステータスを追加したところ表示されました。
