### ISSUE TITLE
フロント画面で商品を購入時にエラーが発生する

### ISSUE THREAD

**Issue by kanako-kina** [EC-CUBE/data-migration-plugin#6]
## 概要(Overview)
2.12系のバックアップデータを4.02系(以下、4系)に引継ぎ後、フロント画面で商品を購入時にエラーが発生する。

## 再現手順(Procedure)
+ 2.12系でテスト用の[会員、管理者、商品、カテゴリ、受注、支払方法、配送方法、税設定、メルマガテンプレート]データを作成。
+ 2.12系でバックアップデータを作成。
+ 4系の環境にバックアップデータを引継ぐ。
+ 4系の環境で、[会員、管理者、商品、カテゴリ、受注、支払方法、配送方法、税設定、メルマガテンプレート]のテストデータを作成。
+ フロント画面で会員情報でログインする。
+ 商品を購入すると、システムエラーが発生。

### 移行前環境 (environment)
+ EC-CUBE：2.12.6
+ DB:
  - PostgreSQL 9.2.23
+ PHP：5.4.16

### 移行後環境 (environment)
+ EC-CUBE：4.0.2
+ DB:
  - PostgreSQL 9.2.24
+ PHP：7.1.21

### 使用したバックアップファイル
[2.12.6-pgsql-backup.tar.gz](https://github.com/EC-CUBE/data-migration-plugin/files/3256124/2.12.6-pgsql-backup.tar.gz)
### 発生時のエラーログ
[error_log.txt](https://github.com/EC-CUBE/data-migration-plugin/files/3256132/error_log.txt)

**Comment by nobuhiko** [comment]
ありがとうございます
修正しました
