### ISSUE TITLE
受注データを管理画面から作成しようとすると、システムエラーが発生する

### ISSUE THREAD

**Issue by kanako-kina** [EC-CUBE/data-migration-plugin#7]
## 概要(Overview)
+ Postgres2.11環境のバックアップデータを4系に引き継ぎ、受注データを管理画面から作成しようとすると、システムエラーが発生する。

## 再現手順(Procedure)
・2.11系でテスト用の[会員、管理者、商品、カテゴリ、受注、支払方法、配送方法、税設定、メルマガテンプレート]データを作成
・2.11系でバックアップデータを作成。
・4系の環境にバックアップデータを引継ぐ。
・4系の環境で、[会員、管理者、商品、カテゴリ、受注、支払方法、配送方法、税設定、メルマガテンプレート]のテストデータを作成。

### 移行前環境 (environment)
+ EC-CUBE：2.11.5
+ DB:
  - PostgreSQL 9.2.23
+ PHP：5.4.16

### 移行後環境 (environment)
+ EC-CUBE：4.0.2
+ DB:
  - PostgreSQL 9.2.24
+ PHP：7.1.21

### 使用したバックアップファイル
[2.11.5-pgsql-backup.tar.gz](https://github.com/EC-CUBE/data-migration-plugin/files/3256174/2.11.5-pgsql-backup.tar.gz)

### 発生時のエラーログ
[error.log](https://github.com/EC-CUBE/data-migration-plugin/files/3256175/error.log)

**Comment by nobuhiko** [comment]
https://github.com/EC-CUBE/data-migration-plugin/issues/6 と同じ内容なので修正済みです

**Comment by kanako-kina** [comment]
もう一度確認してみましたが、
移行後に管理画面より受注作成を行うとPostgreSQL 環境でシステムエラーが発生しました。
同じバックアップデータを使用しましたがMysqlの環境では発生しません。

### 使用したバックアップファイル
[211-pgsql20190614.tar.gz](https://github.com/EC-CUBE/data-migration-plugin/files/3289652/211-pgsql20190614.tar.gz)


### 発生時のエラーログ
[error.log](https://github.com/EC-CUBE/data-migration-plugin/files/3289645/error.log)

**Comment by kanako-kina** [comment]
表示を確認できました。修正ありがとうございます。
