### ISSUE TITLE
支払方法の利用条件の下限値が引き継がれていない

### ISSUE THREAD

**Issue by kanako-kina** [EC-CUBE/data-migration-plugin#8]
## 概要(Overview)
2.11系で作成した支払方法を4系に引き継いだ時、支払方法の利用条件の下限値が引き継がれていない。

## 再現手順(Procedure)
+ 2.11系でテスト用の[会員、管理者、商品、カテゴリ、受注、支払方法、配送方法、税設定、メルマガテンプレート]データを作成
+ 2.11系でバックアップデータを作成。
+ 4系の環境にバックアップデータを引継ぐ。
+ 管理画面で設定 > 支払方法設定で2.11系環境でバックアップ用に作成した支払方法は利用条件の部分で料金の下限値と上限値を割り当てているが、下限値が引き継がれていない。

### 移行前環境 (environment)
+ EC-CUBE：2.11.5
+ DB:
  - PostgreSQL 9.2.23
+ PHP：5.4.16

### 移行後環境 (environment)
+ EC-CUBE：4.0.2
+ DB:
  - PostgreSQL 9.2.24
+ PHP：7.1.21

**Comment by nobuhiko** [comment]
修正しました

**Comment by kanako-kina** [comment]
修正されていることを確認しました。
ご対応いただきありがとうございます。
