### ISSUE TITLE
受注データの取り込み時、特定のテーブルをスキップしたい

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/data-migration-plugin#9]
## 概要
受注データ取り込み時、dtb_payment, dtb_delivery等をスキップしたい

## 移行のステップ
予定しているサイト移行のステップは以下の通り

1. 旧サイトから新サイトへの移行準備期間
    1. 旧サイトのデータをいったん移行する
    1. データ移行プラグインで対象外になっている商品画像や、フリーエリアの更新を行う
    1. 決済プラグイン・支払方法の設定を行う
1. サイト切り替え当日に、会員・受注データを移行する
    1. 旧サイトをメンテナンス状態に変更
    1. 旧サイトでバックアップデータ取得
    1. 新サイトにて、会員・受注データを投入

## 修正案

2-3で、バックアップデータからdtb_products.csvを除けば会員・受注データのみ移行できるが、1-3で設定した支払方法が初期化されてしまう。

saveToO()で、ファイルがなければスキップするようにしたい。

https://github.com/EC-CUBE/data-migration-plugin/blob/master/Controller/Admin/ConfigController.php#L903

**Comment by nobuhiko** [comment]
ファイルがなければスキップするようにしていないのは、初回にそれをするとリレーションがおかしくなるからなのです

**Comment by chihiro-adachi** [comment]
そうなんですね。

初回は全データを一旦移行し、直前の取り込みではバックアップデータからdtb_products.csv/dtb_payment.csvを除いて移行する、みたいなオペレーションにしようかと思っていました。

**Comment by nobuhiko** [comment]
運用する際に、コード書き換えれば対応出来ると思います。
プラグインとしてそれを対応しようとすると変なシステムエラーが増えると思うので、どうしたものかなと。

あと、圧縮がコマンドラインで対応しないとダメだったりするので色々微妙なんですよね。。

**Comment by chihiro-adachi** [comment]
> 運用する際に、コード書き換えれば対応出来ると思います。
あー、やっぱりそうですよね。その方向で検討してみます。

**Comment by chihiro-adachi** [comment]
#32 で会員と受注のみ移行するオプションを実装したので、こちらのissueはクローズします。
